### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by DevDorrejo** [quickemu-project/quickgui#10]
Hello, i am trying to compile, because the one compiled on release not work on my machine.

![image](https://user-images.githubusercontent.com/7697566/140821891-6b3dc2e3-932e-41f6-b520-26e4e531ac9f.png)

CMAKE logs
[CMakeOutput.log](https://github.com/quickgui/quickgui/files/7500295/CMakeOutput.log)
[CMakeCache.txt](https://github.com/quickgui/quickgui/files/7500297/CMakeCache.txt)

**Comment by philclifford** [comment]
Hi, quick question. Are you building on OpenSUSE ?

**Comment by DevDorrejo** [comment]
> Hi, quick question. Are you building on OpenSUSE ?

yes

**Comment by philclifford** [comment]
Can you share the output of `flutter doctor`, only it appears from the logs you may be missing some of the needed toolchain ( e.g. `ar` isn't found ). I'm guessing here, but trying to get enough info to move forward.

**Comment by DevDorrejo** [comment]
Found with doctor, that i need to install gtk3-devel.

is good to put on the doc:

for build

enable flutter linux build
flutter config --enable-linux-desktop

opensuse requiremente
zypper in gtk3-devel

after compiling and executing:

![image](https://user-images.githubusercontent.com/7697566/140827687-5955e563-16e0-4c01-a134-52d4ed203db3.png)

**Comment by DevDorrejo** [comment]
quickemu work normally, but quickgui no

![image](https://user-images.githubusercontent.com/7697566/140828061-c9a373e5-77c2-4441-a33e-974e478c08fe.png)

**Comment by philclifford** [comment]
are you in `<quickgui_src>/build/linux/release/bundle/` ? You maybe just need to execute `.//build/linux/release/bundle/quickgui` if you're at the top of the source after building.

**Comment by DevDorrejo** [comment]
> are you in `<quickgui_src>/build/linux/release/bundle/` ? You maybe just need to execute `./build/linux/release/bundle/quickgui` if you're at the top of the source after building.

this is the folder that is created on the build:
`./build/linux/x64/release/intermediates_do_not_run/quickgui`

**Comment by philclifford** [comment]
Hmm, that looks to me as if you still don't quite have a working build environment.  Beyond my capacity to help here (not a flutter dev and not used OpenSuSE since 10.x days ) but maybe a bit of google-fu can find a guide (post or person) that can get you to a completed build.  Something similar to the Ubuntu-based guide linked in the Readme.  The one that a quick search suggested to me is [here](https://javascriptsu.wordpress.com/2020/11/24/how-to-enable-flutter-desktop-support-in-opensuse-linux/) but you may find better. Working through to a running example/test desktop app should hopefully put you in a position to build this successfully.  
I'm surprised that just unpacking the [release archive](https://github.com/quickgui/quickgui/releases/download/v1.1.1/quickgui-1.1.1.tar.xz) somewhere and running it from there doesn't work for you: it is supposed to be portable after all, and works fine for me (and others clearly) so if there's an OpenSUSE-specific problem we'll need to sort that too - thankfully we can `quickget opensuse ...`  . Some more detail on how the release fails for you might help, along with what release/version of OpenSUSE you're running. Hopefully then smarter eyes than mine can take a look.

**Comment by DevDorrejo** [comment]
Thank.

The links have nothing of the website not share nothing new to me.

And is weird that isn't working neither the release version.

**Comment by DevDorrejo** [comment]
i am using Tumbleweed.

**Comment by ymauray** [comment]
> Found with doctor, that i need to install gtk3-devel.
> 
> is good to put on the doc:
> 
> for build
> 
> enable flutter linux build flutter config --enable-linux-desktop
> 
> opensuse requiremente zypper in gtk3-devel

I don't think I'll put that in the doc. It's a "install flutter properly" problem, not a quickgui problem. Besides, I can't put in the doc everything everyone has to do on every distro to install flutter.

**Comment by ymauray** [comment]
> intermediates_do_not_run

That's your clue :-) Do not run a binaray that is in a folder names "do_not_run".

As @philclifford said, you probably still have a problem with your flutter installation.

Try this : 
```cd /tmp
flutter create helloworld
cd helloworld
flutter build linux --release
./build/linux/x64/release/bundle/helloworld
```

You should have the default app running.

**Comment by ymauray** [comment]
Also, as @philclifford said, why are you not using the provided binaray files ? Did you try to go to https://github.com/quickgui/quickgui/releases/tag/v1.1.1, and download quickgui-1.1.1.tar.xz ?

**Comment by DevDorrejo** [comment]
Don't know what happened, but with the version 1.1.2 is working now.

thanks for the patience and support.

**Comment by DevDorrejo** [comment]
NAME="openSUSE Tumbleweed"
# VERSION="20211107"
KDE Plasma 5.23.2

**Comment by ymauray** [comment]
Do you still have a problem with this ?

**Comment by ymauray** [comment]
I think I have an idea.
Where is `quickget` installed ? 
I bet `quickget` is not in the PATH when you use the file manager, but it is when you run from a terminal.
Can you check that ?

**Comment by DevDorrejo** [comment]
> I think I have an idea. Where is `quickget` installed ? I bet `quickget` is not in the PATH when you use the file manager, but it is when you run from a terminal. Can you check that ?

![image](https://user-images.githubusercontent.com/7697566/141851958-7939f678-2fdc-49e4-98e5-7e1f0508b49f.png)
