### ISSUE TITLE
Windows distros missing from quickemu GUI

### ISSUE THREAD

**Issue by PPKNexus** [quickemu-project/quickgui#116]
After selection the create new machine option on the GUI, it brings up a list of distros to download and install(as it should).

However, within this list, there are now distros entirely missing from the download list that were once there. Namely, Windows. There may be others, but this was the only one I'm aware of.
![QuickemuListWinMiss](https://github.com/quickemu-project/quickemu/assets/121834217/cdb92472-93ec-4730-9572-316cb7d3248f)

**NOTE: The quickget command line still seems to work fine for installing it, so it appears to just be a quickGUI thing it seems.
![quickgetWindows](https://github.com/quickemu-project/quickemu/assets/121834217/4bfcd0f0-2e89-4fe7-876d-ec4f383dddff)

LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by halian** [comment]
Can confirm this issue is present in 1.2.8-1 under Arch Linux. (Mac OS X is also missing.)

**Comment by MMachado05** [comment]
Can confirm this is still a problem, running Kubuntu 22.04.3 on my main device.

**Comment by lj3954** [comment]
This is a bug in quickget, not in quickgui. It should be moved back to the quickemu repository. Specifically, it's caused by lines 193-196, in which the quickget list_csv function prints out an entry for windows **for each value in the language array.** Windows language support was removed in quickemu commit 008478d, which 'fixed' downloading windows ISOs by using a third-party source (which has since been changed). The language array is left blank though, so quickget list_csv does not print out any entries for windows.

My pull request on the quickemu repository (https://github.com/quickemu-project/quickemu/pull/886) re-implements language support for windows. This fixes the issue, as is evidenced by my testing in a Linux Mint VM.

**Comment by PPKNexus** [comment]
@flexiondotorg Thank you for the update!
