### ISSUE TITLE
triage: window controls aren't in the corner of the window on KDE

### ISSUE THREAD

**Issue by popey** [quickemu-project/quickgui#85]
Using quickgui from tip of git.

If I build using flutter 3.3.8 on Ubuntu 22.10 (Kubuntu) and run, the `X` window close button is offset from the corner of the window. I don't know if this is a flutter or quickgui issue.

![image](https://user-images.githubusercontent.com/1841272/201520968-c2d8abb8-3fdd-43a0-bb5a-5b35e38ba71d.png)

I'd expect the close icon to be in a similar location to other applications.

**Comment by ymauray** [comment]
Interesting. I would say it's a Window Manager thing, but more investigation is required.

**Comment by flexiondotorg** [comment]
Tested on KDE Neon (22.04 / Plasma 6) and Kubuntu (24.04 / Plasma 5).

This issue is present on Plasma 5, but not on Plasma 6. So, as @ymauray suspected it does look to be a window manager related issue that has been addressed in Plasma 6.

Closing this as it is not a Quickgui issue :slightly_smiling_face:
